In [23]:
import numpy as np
import pandas as pd

from submit_result import * #create_real_pred
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier

from dotenv import load_dotenv
load_dotenv(r'.env')
import os
data_dir = os.environ.get('DATA_DIR')

In [2]:
data_train = pd.read_csv(data_dir + "/sign_mnist_train.csv")
data_test = pd.read_csv(data_dir + "/test.csv")

In [3]:
np.unique(data_train['label'])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int64)

In [4]:
X_train, X_val, y_train, y_val = train_test_split(data_train.iloc[:,1:], data_train['label'], test_size=0.1, stratify=data_train['label'], random_state=21)
#X_train = data_train.iloc[:,1:]
#y_train = data_train['label']

In [5]:
X_train.head(1)

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
8375     131     135     138     139     142     144     146     146     147   

      pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
8375      147  ...        87        82       115       171       203   

      pixel780  pixel781  pixel782  pixel783  pixel784  
8375       200       175       145       147       178  

[1 rows x 784 columns]

In [6]:
#model = RandomForestClassifier(max_depth=15, criterion="entropy")
model = AdaBoostClassifier(n_estimators=50, random_state=42)
print(model)

RandomForestClassifier(criterion='entropy', max_depth=15)


In [7]:
model.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', max_depth=15)

In [8]:
pred = model.predict(X_val)
(pred == y_val).mean()

0.9981791697013839

In [9]:
data_test.head(2)

id  pixel_a1  pixel_a2  pixel_a3  pixel_a4  pixel_a5  pixel_a6  pixel_a7  \
0   0       225       227       227       228       229       229       227   
1   1       190       191       190       191       190       190       192   

   pixel_a8  pixel_a9  ...  pixel_b775  pixel_b776  pixel_b777  pixel_b778  \
0       227       227  ...         163         164         164         162   
1       192       191  ...         110          89          82          86   

   pixel_b779  pixel_b780  pixel_b781  pixel_b782  pixel_b783  pixel_b784  
0         163         162         162         161         161         158  
1         134         186         188         190         190         191  

[2 rows x 1569 columns]

In [10]:
test_A = data_test.iloc[:,1:785]
test_B = data_test.iloc[:,785:]
nouveaux_noms = [f"pixel{i+1}" for i in range(len(test_A.columns))]

# Attribuez ces nouveaux noms aux colonnes du DataFrame
test_A.columns = nouveaux_noms
test_B.columns = nouveaux_noms

In [11]:
test_A.head(1)

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0     225     227     227     228     229     229     227     227     227   

   pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0      227  ...        47        48        23        17        29        37   

   pixel781  pixel782  pixel783  pixel784  
0        43        38        37        43  

[1 rows x 784 columns]

In [12]:
test_B.head(1)

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0     138     140     141     143     146     147     147     148     149   

   pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0      149  ...       163       164       164       162       163       162   

   pixel781  pixel782  pixel783  pixel784  
0       162       161       161       158  

[1 rows x 784 columns]

In [13]:
pred_A = model.predict(test_A)
pred_B = model.predict(test_B)

In [14]:
print(pred_A)
print(pred_B)

[ 6  2  1 ... 23  4 19]
[ 6 22  5 ... 19 14  2]


In [15]:
pred_final = create_real_pred(pred_A, pred_B)

In [16]:
submit = pd.concat([data_test['id'], pred_final], axis = 1)

In [17]:
submit

id label
0        0     M
1        1     Y
2        2     G
3        3     S
4        4     \
...    ...   ...
2995  2995     m
2996  2996     ^
2997  2997     k
2998  2998     S
2999  2999     V

[3000 rows x 2 columns]

In [18]:
submit.to_csv("results/submit_4_adaboost_sklearn.csv", index=False)

In [19]:
t = [4, 5, 1]
v = [1, 3, 23]

In [20]:
a1 = convert_ascii(t)
a2 = convert_ascii(v)
print(a1, a2)

[69, 70, 66] [66, 68, 88]


In [21]:
l1 = convert_asci_lettre(a1)
l2 = convert_asci_lettre(a2)
print(l1)
print(l2)

0    E
1    F
2    B
Name: label, dtype: object
0    B
1    D
2    X
Name: label, dtype: object


In [22]:
create_real_pred(t, v)

0    F
1    I
2    Y
Name: label, dtype: object